name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.architecture }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/infinity-nft:${{ matrix.architecture }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Container
        run: |
          ssh -t -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e
          echo "Stopping existing container if it exists..."
          docker stop infinity-nft || true
          echo "Removing existing container if it exists..."
          docker rm infinity-nft
          echo "Removing existing image if it exists..."
          docker rmi ${{ vars.DOCKERHUB_USERNAME }}/infinity-nft:amd64 || true
          echo "Pulling Docker image..."
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/infinity-nft:amd64
          echo "Running new container..."
          docker run -d --name infinity-nft -p 8081:5678 ${{ vars.DOCKERHUB_USERNAME }}/infinity-nft:amd64
          echo "Restarting NGINX..."
          sudo systemctl restart nginx
          echo "Deployment completed!"
          EOF
